version: '3.4'
volumes:
  pg_data: {}

services:
  app:
    build:
      context: .
      args:
        ENVIRONMENT: local
    env_file:
      - ./environments/.env
    volumes:
      - ./app:/app
      - /tmp/:/tmp/
    ports:
      - '8080:8080'
    links:
      - postgres

    restart: 'always'
    command: >
      sh -c 'python manage.py wait_for_db && python manage.py runserver 0.0.0.0:8080'
    # command: ['python', 'manage.py', 'runserver', '0.0.0.0:8080']

  postgres:
    image: postgres:13.4-alpine
    env_file:
      - ./environments/.env
    volumes:
      - pg_data:/var/lib/postgresql/data
