# Generated by Django 3.2.16 on 2023-01-28 09:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]
    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation', django.contrib.postgres.fields.jsonb.JSONField(default={'hi': 'hello'})),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'article',
            },
        )
    ]
